name: ChiselStage


on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, develop, feature/actionTest ]
  # pull_request:
  #   branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  # clean:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
    # steps:

    #   - name: cleanCommit
    #     run: |
    #       cd /Users/runner/work/RiftCore/
    #       git clone https://github.com/whutddk/RiftCore/
    #       cd RiftCore/
    #       git fetch --all
    #       git checkout gh-pages
    #       git reset --hard 4e5a
 
    #   - name: cleanPush
    #     uses: ad-m/github-push-action@master
    #     with:
    #       github_token: ${{ secrets.GITHUB_TOKEN }}
    #       branch: gh-pages
    #       force: true
  build:
    # The type of runner that the job will run on
    runs-on: macos-12
    # needs: clean
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Compile
        run: |
          git submodule update --init --recursive
          sbt "test:runMain test.testAll"
          sbt doc

          echo $GITHUB_REF_NAME
          
          mkdir /Users/runner/work/Rift2Core/ScalaDoc/
          mkdir /Users/runner/work/Rift2Core/ScalaDoc/$GITHUB_REF_NAME/

          cd /Users/runner/work/Rift2Core/Rift2Core/

          cp -R target/scala-2.12/api /Users/runner/work/Rift2Core/ScalaDoc/$GITHUB_REF_NAME

          tar -cvf Rift2330-Release.tar ./generated/Release/Rift2330
          tar -cvf Rift2330-Debug.tar ./generated/Debug/Rift2330

      # mkdir /Users/runner/work/Rift2Core/Verilog/
      # mkdir /Users/runner/work/Rift2Core/Verilog/$GITHUB_REF_NAME/
      # cp -R generated/Release /Users/runner/work/Rift2Core/Verilog/$GITHUB_REF_NAME 
      # - name: Restore Data
      #   run: |
      #     cd /Users/runner/work/Rift2Core/Rift2Core/
      #     git fetch --all
      #     git checkout origin/gh-pages data/performance.js
      #     cp data/performance.js tb/ci/
      #     cp ~/riscv-tests/benchmarks/*.verilog tb/ci/

      # rm -rf /Users/runner/work/Rift2Core/Rift2Core/Verilog/$GITHUB_REF_NAME  
      # cp -R /Users/runner/work/Rift2Core/Verilog/$GITHUB_REF_NAME /Users/runner/work/Rift2Core/Rift2Core/Verilog/$GITHUB_REF_NAME
      - name: Commit
        run: |
          cd /Users/runner/work/Rift2Core/Rift2Core
          git checkout -- .
          git fetch --all
          git checkout gh_pages

          rm -rf /Users/runner/work/Rift2Core/Rift2Core/ScalaDoc/$GITHUB_REF_NAME
          cp -R /Users/runner/work/Rift2Core/ScalaDoc/$GITHUB_REF_NAME /Users/runner/work/Rift2Core/Rift2Core/ScalaDoc/$GITHUB_REF_NAME

          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add ./ScalaDoc
          git commit --allow-empty -m "update ci result"
 
      - name: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh_pages
          force: false


      - name: Create Release and Upload Release Asset
        run: |
          echo $GITHUB_REF_NAME
        if: GITHUB_REF_NAME != 'master'
          uses: softprops/action-gh-release@v1
          with:
            # tag_name: $GITHUB_SHA
            name: Rift2xx0
            # body: TODO New Release.
            draft: false
            prerelease: true
            files: |
              Rift2330-Release.tar
              Rift2330-Debug.tar
              LICENSE.Apache
              LICENSE.NPL
        if: GITHUB_REF_NAME == 'master'
          uses: softprops/action-gh-release@v1
          with:
            # tag_name: $GITHUB_SHA
            name: Rift2xx0
            # body: TODO New Release.
            draft: false
            prerelease: false
            files: |
              Rift2330-Release.tar
              Rift2330-Debug.tar
              LICENSE.Apache
              LICENSE.NPL

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
